namespace UncomplicatedCustomItems.Enums
{
    public enum EffectCheck
    {
        None = 0,
        AmnesiaItems = 1,
        AmnesiaVision = 2,
        Asphyxiated = 3,
        Bleeding = 4,
        Blinded = 5,
        Burned = 6,
        Concussed = 7,
        Corroding = 8,
        Deafened = 9,
        Decontaminating = 10,
        Disabled = 11,
        Ensnared = 12,
        Exhausted = 13,
        Flashed = 14,
        Hemorrhage = 15,
        Invigorated = 16,
        BodyshotReduction = 17,
        Poisoned = 18,
        Scp207 = 19,
        Invisible = 20,
        SinkHole = 21,
        DamageReduction = 22,
        MovementBoost = 23,
        RainbowTaste = 24,
        SeveredHands = 25,
        Stained = 26,
        Vitality = 27,
        Hypothermia = 28,
        Scp1853 = 29,
        CardiacArrest = 30,
        InsufficientLighting = 31,
        SoundtrackMute = 32,
        SpawnProtected = 33,
        Traumatized = 34,
        AntiScp207 = 35,
        Scanned = 36,
        PocketCorroding = 37,
        SilentWalk = 38,
        Strangled = 40,
        Ghostly = 41,
        FogControl = 42,
        Slowness = 43,
        Scp1344 = 44,
        SeveredEyes = 45,
        PitDeath = 46,
        Blurred = 47, 
    }
}
