<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net48</TargetFramework>
    <RootNamespace>UncomplicatedCustomItems</RootNamespace>
    <AssemblyName>UncomplicatedCustomItems</AssemblyName>
    <LangVersion>14</LangVersion>
    <Deterministic>true</Deterministic>
    <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    <Configuration Condition=" '$(Configuration)' == '' ">LabApi-Debug</Configuration>
    <Platform Condition=" '$(Platform)' == '' ">x64</Platform>
    <Configurations>Exiled;LabApi;Exiled-Debug;LabApi-Debug</Configurations>
    <Nullable>enable</Nullable>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
  </PropertyGroup>

  <PropertyGroup Condition=" '$(Configuration)' == 'LabApi' ">
    <DefineConstants>LABAPI</DefineConstants>
    <AssemblyName>UncomplicatedCustomItems-LabApi</AssemblyName>
    <OutputPath>bin\LabAPI\</OutputPath>
    <DebugType>embedded</DebugType>
    <Optimize>true</Optimize>
  </PropertyGroup>

  <PropertyGroup Condition=" '$(Configuration)' == 'Exiled' ">
    <DefineConstants>EXILED</DefineConstants>
    <AssemblyName>UncomplicatedCustomItems-Exiled</AssemblyName>
    <OutputPath>bin\Exiled\</OutputPath>
    <DebugType>embedded</DebugType>
    <Optimize>true</Optimize>
  </PropertyGroup>

  <PropertyGroup Condition=" '$(Configuration)' == 'LabApi-Debug' ">
    <DefineConstants>LABAPI;DEBUG;TRACE</DefineConstants>
    <AssemblyName>UncomplicatedCustomItems-LabApi</AssemblyName>
    <OutputPath>bin\LabAPI-Debug\</OutputPath>
    <DebugType>full</DebugType>
    <DebugSymbols>true</DebugSymbols>
    <Optimize>false</Optimize>
  </PropertyGroup>

  <PropertyGroup Condition=" '$(Configuration)' == 'Exiled-Debug' ">
    <DefineConstants>EXILED;DEBUG;TRACE</DefineConstants>
    <AssemblyName>UncomplicatedCustomItems-Exiled</AssemblyName>
    <OutputPath>bin\Exiled-Debug\</OutputPath>
    <DebugType>full</DebugType>
    <DebugSymbols>true</DebugSymbols>
    <Optimize>false</Optimize>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Northwood.LabAPI" Version="1.1.7" Publicize="true" />
    <PackageReference Include="ExMod.Exiled" Version="9.14.2" Condition=" '$(Configuration)' == 'Exiled' Or '$(Configuration)' == 'Exiled-Debug'" />
    <PackageReference Include="Lib.Harmony" Version="2.2.2" />
    <PackageReference Include="System.Text.Json" Version="10.0.8" />
    <PackageReference Include="BepInEx.AssemblyPublicizer.MSBuild" Version="0.4.*" />
  </ItemGroup>

  <ItemGroup>
    <Reference Include="Assembly-CSharp" Publicize="true" HintPath="$(SL_REFERENCES)\Assembly-CSharp.dll" />
    <Reference Include="Mirror" Publicize="true" HintPath="$(SL_REFERENCES)\Mirror.dll" />
    <Reference Include="NorthwoodLib" HintPath="$(SL_REFERENCES)\NorthwoodLib.dll" />
    <Reference Include="Microsoft.CSharp" />
    <Reference Include="Assembly-CSharp-firstpass" Publicize="true" HintPath="$(SL_REFERENCES)\Assembly-CSharp-firstpass.dll" />
    <Reference Include="BouncyCastle.Cryptography" HintPath="$(SL_REFERENCES)\BouncyCastle.Cryptography.dll" />
    <Reference Include="Caress" HintPath="$(SL_REFERENCES)\Caress.dll" />
    <Reference Include="CommandSystem.Core" HintPath="$(SL_REFERENCES)\CommandSystem.Core.dll" />
    <Reference Include="Mirror.Components" HintPath="$(SL_REFERENCES)\Mirror.Components.dll" />
    <Reference Include="Mono.Security" HintPath="$(SL_REFERENCES)\Mono.Security.dll" />
    <Reference Include="UnityEngine.UnityWebRequestModule" HintPath="$(SL_REFERENCES)\UnityEngine.UnityWebRequestModule.dll" />
    <Reference Include="Pooling" HintPath="$(SL_REFERENCES)\Pooling.dll" />
    <Reference Include="System" />
    <Reference Include="System.Net.Http" />
    <Reference Include="System.Runtime.CompilerServices.Unsafe" HintPath="$(SL_REFERENCES)\System.Runtime.CompilerServices.Unsafe.dll" />
    <Reference Include="Unity.Mathematics" HintPath="$(SL_REFERENCES)\Unity.Mathematics.dll" />
    <Reference Include="UnityEngine" HintPath="$(SL_REFERENCES)\UnityEngine.dll" />
    <Reference Include="UnityEngine.CoreModule" HintPath="$(SL_REFERENCES)\UnityEngine.CoreModule.dll" />
    <Reference Include="UnityEngine.AudioModule" HintPath="$(SL_REFERENCES)\UnityEngine.AudioModule.dll" />
    <Reference Include="UnityEngine.PhysicsModule" HintPath="$(SL_REFERENCES)\UnityEngine.PhysicsModule.dll" />
    <Reference Include="YamlDotNet" HintPath="$(SL_REFERENCES)\YamlDotNet.dll" />
  </ItemGroup>

  <ItemGroup>
    <None Include="Properties\AssemblyInfo.cs" />
  </ItemGroup>

  <ItemGroup>
    <None Include="app.config" />
  </ItemGroup>
  
  <Target Name="PostBuildCopyExiled" AfterTargets="Build" Condition="'$(Configuration)' == 'Exiled' Or '$(Configuration)' == 'Exiled-Debug'">
    <Message Text="Copying UncomplicatedCustomItems-Exiled.dll to EXILED plugin folder..." Importance="high" />
    <Copy SourceFiles="$(OutputPath)UncomplicatedCustomItems-Exiled.dll" DestinationFolder="$(APPDATA)\EXILED\Plugins" SkipUnchangedFiles="true" Condition="'$(OS)' == 'Windows_NT'" />
    <Copy SourceFiles="$(OutputPath)UncomplicatedCustomItems-Exiled.dll" DestinationFolder="$(HOME)/.config/EXILED/Plugins" SkipUnchangedFiles="true" Condition="'$(OS)' != 'Windows_NT'" />
  </Target>

  <Target Name="PostBuildCopyLabApi" AfterTargets="Build" Condition="'$(Configuration)' == 'LabApi' Or '$(Configuration)' == 'LabApi-Debug'">
    <Message Text="Copying UncomplicatedCustomItems-LabApi.dll to LabAPI plugin folder..." Importance="high" />
    <Copy SourceFiles="$(OutputPath)UncomplicatedCustomItems-LabApi.dll" DestinationFolder="$(APPDATA)\SCP Secret Laboratory\LabAPI\plugins\global" SkipUnchangedFiles="true" Condition="'$(OS)' == 'Windows_NT'" />
    <Copy SourceFiles="$(OutputPath)UncomplicatedCustomItems-LabApi.dll" DestinationFolder="$(HOME)/.config/SCP Secret Laboratory/LabAPI/plugins/global" SkipUnchangedFiles="true" Condition="'$(OS)' != 'Windows_NT'" />
  </Target>
</Project>